version: '3'

networks: 
  mvc:


services: 

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "8088:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - mysql
      - php
    networks:
      - mvc

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql    
    networks:
      - mvc
  
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src:/var/www/html
    ports: 
      - "9000:9000"
    networks:
      - mvc

  composer: 
    image: composer:latest
    container_name: composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks: 
      - mvc
  # docker-compose run --rm composer -v   


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on: 
      - mysql
    ports: 
      - "8087:80"
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks: 
      - mvc

